name: Deno CI (test)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Check format
        run: deno fmt --check

      - name: Check linting
        run: deno lint

    #   - name: Tests
    #     run: deno task test

    #   - name: Coverage
    #     run: deno task coverage

    # Disabled for now
    #   - name: Upload coverage reports to Codecov
    #     uses: codecov/codecov-action@v3
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #       file: ./.coverage/coverage.lcov
    #       flags: unittests
    #       name: codecov-umbrella
    #       fail_ci_if_error: true
